import { createEnv } from '@t3-oss/env-nextjs'
import { z } from 'zod'

export const env = createEnv({
  server: {
    ADMIN_EMAIL: z.string().email(),
    POSTGRES_USER: z.string().min(1),
    POSTGRES_PASSWORD: z.string().min(1),
    POSTGRES_DB: z.string().min(1),
    POSTGRES_DATABASE: z.string().min(1),
    POSTGRES_HOST: z.string().min(1),
    POSTGRES_URL: z.string().startsWith('postgres://'),
    POSTGRES_PRISMA_URL: z.string().startsWith('postgres://'),
    POSTGRES_URL_NON_POOLING: z.string().startsWith('postgres://'),
    STRIPE_PUBLISHABLE_KEY: z.string().startsWith('pk_live_'),
    STRIPE_SECRET_KEY: z.string().startsWith('sk_live_'),
    STRIPE_WEBHOOK_SECRET: z.string().min(1),
    STRIPE_PRO_MONTHLY_PLAN_ID: z.string().min(1),
    OPENAI_API_KEY: z.string().startsWith('sk-'),
    OPENAI_ORGANIZATION_ID: z.string().min(1),
    OPENAI_ASSISTANT_ID: z.string().startsWith('asst_'),
    CLERK_SECRET_KEY: z.string().startsWith('sk_'),
    POSTMARK_SECRET_KEY: z.string(),
    CLERK_WEBHOOK_SIGNING_SECRET: z.string().min(1),
  },
  client: {
    NEXT_PUBLIC_APP_NAME: z.string().min(1),
    NEXT_PUBLIC_APP_URL: z.string().url(),
    NEXT_PUBLIC_APP_EMAIL: z.string().email(),
    NEXT_PUBLIC_APP_COMPANY: z.string().min(1),
    NEXT_PUBLIC_APP_ADDRESS: z.string().min(1),
    NEXT_PUBLIC_BILLING_URL: z.string().startsWith('/'),
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string().startsWith('pk_'),
    NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: z.string().startsWith('/'),
    NEXT_PUBLIC_LO_SITE_ID: z.string().min(1),
    NEXT_PUBLIC_POSTMARK_SENDER_NAME: z.string().min(1),
  },
  runtimeEnv: {
    ADMIN_EMAIL: process.env.ADMIN_EMAIL,
    NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_APP_EMAIL: process.env.NEXT_PUBLIC_APP_EMAIL,
    NEXT_PUBLIC_APP_COMPANY: process.env.NEXT_PUBLIC_APP_COMPANY,
    NEXT_PUBLIC_APP_ADDRESS: process.env.NEXT_PUBLIC_APP_ADDRESS,
    NEXT_PUBLIC_BILLING_URL: process.env.NEXT_PUBLIC_BILLING_URL,
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
    NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: process.env.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL,
    POSTGRES_USER: process.env.POSTGRES_USER,
    POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD,
    POSTGRES_DB: process.env.POSTGRES_DB,
    POSTGRES_DATABASE: process.env.POSTGRES_DATABASE,
    POSTGRES_HOST: process.env.POSTGRES_HOST,
    POSTGRES_URL: process.env.POSTGRES_URL,
    POSTGRES_PRISMA_URL: process.env.POSTGRES_PRISMA_URL,
    POSTGRES_URL_NON_POOLING: process.env.POSTGRES_URL_NON_POOLING,
    STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    STRIPE_PRO_MONTHLY_PLAN_ID: process.env.STRIPE_PRO_MONTHLY_PLAN_ID,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    OPENAI_ORGANIZATION_ID: process.env.OPENAI_ORGANIZATION_ID,
    OPENAI_ASSISTANT_ID: process.env.OPENAI_ASSISTANT_ID,
    CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
    NEXT_PUBLIC_LO_SITE_ID: process.env.NEXT_PUBLIC_LO_SITE_ID,
    POSTMARK_SECRET_KEY: process.env.POSTMARK_SECRET_KEY,
    NEXT_PUBLIC_POSTMARK_SENDER_NAME: process.env.NEXT_PUBLIC_POSTMARK_SENDER_NAME,
    CLERK_WEBHOOK_SIGNING_SECRET: process.env.CLERK_WEBHOOK_SIGNING_SECRET,
  },
})
